// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB37VSf9Y2C__cHWBss0JTINJgXLfuUWsY',
    appId: '1:420749339844:web:3b7788498fbb221a21ad91',
    messagingSenderId: '420749339844',
    projectId: 'chat-together-12527',
    authDomain: 'chat-together-12527.firebaseapp.com',
    storageBucket: 'chat-together-12527.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAst78IFDbNS9SoatIYMWS8ylavb5Fn300',
    appId: '1:420749339844:android:a50b4933657d069221ad91',
    messagingSenderId: '420749339844',
    projectId: 'chat-together-12527',
    storageBucket: 'chat-together-12527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgD0w4BxhO7vZLBxmeVtU2n9_bSWf6Wq8',
    appId: '1:420749339844:ios:abf4ddd37d58ff5921ad91',
    messagingSenderId: '420749339844',
    projectId: 'chat-together-12527',
    storageBucket: 'chat-together-12527.appspot.com',
    iosClientId:
        '420749339844-cu5mtckmv8n5b0lqtsngpouoa7456388.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgD0w4BxhO7vZLBxmeVtU2n9_bSWf6Wq8',
    appId: '1:420749339844:ios:abf4ddd37d58ff5921ad91',
    messagingSenderId: '420749339844',
    projectId: 'chat-together-12527',
    storageBucket: 'chat-together-12527.appspot.com',
    iosClientId:
        '420749339844-cu5mtckmv8n5b0lqtsngpouoa7456388.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatTogether',
  );
}
